class Constant:

    # 認証関連
    MAX_USERNAME_LENGTH = 50
    MAX_PASSWORD_LENGTH = 50
    MIN_PASSWORD_LENGTH = 8
    MAX_ACCOUNT_NAME_LENGTH = 30

    # 記事関連
    MAX_CONTENT_MARKDOWN_SIZE = 1 * 1024 * 1024  # 1MB
    MAX_SLUG_LENGTH = 50
    MAX_TITLE_LENGTH = 255
    MAX_THUMBNAIL_URL = 500
    MAX_TAGS = 20
    MAX_TAG_LENGTH = 30
    MAX_KEYWORD_LENGTH = 1000
    MIN_OFFSET = 0
    MIN_LIMIT = 1
    MAX_LIMIT = 30
    MIN_POST_ID = 1
    MIN_PAGE = 1

    # 画像関連
    MAX_FILE_SIZE = 5 * 1024 * 1024  # 5MB
    ALLOWED_EXTENSIONS = {"jpeg", "jpg", "png", "heic"}
    MAX_ALT_TEXT_LENGTH = 255
    MIN_IMAGE_ID = 1

    # 公開記事関連
    PUBLIC_POST_LIMIT = 10

    # 公開API キャッシュ関連
    PUBLIC_CACHE_MAX_AGE = 300  # CDN キャッシュ保持時間(秒)
    PUBLIC_CACHE_CONTROL = f"public, max-age=0, s-maxage={PUBLIC_CACHE_MAX_AGE}"

    # プロフィール関連
    MAX_HEADLINE_LENGTH = 255
    MAX_BIO_LENGTH = 2000
    MAX_SITE_DESCRIPTION_LENGTH = 1000

    # 年表関連
    MIN_YEAR = 1900
    MAX_YEAR = 2100
    MAX_TIMELINE_TITLE_LENGTH = 255
    MAX_TIMELINE_BODY_LENGTH = 2000
    MIN_TIMELINE_ID = 1

    # プロダクト関連
    MAX_PRODUCT_TITLE_LENGTH = 255
    MAX_PRODUCT_DESCRIPTION_LENGTH = 2000
    MAX_LINK_URL_LENGTH = 500
    MIN_PRODUCT_ID = 1

    # 表示順（年表・プロダクト共通）
    MIN_SORT_ORDER = 0
