services:
  api:
    build: .
    env_file:
      - .env.local
    container_name: blog-api
    ports:
      - "8000:8000"
    environment:
      ENV_FILE: .env.local
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    container_name: blog-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_db
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ppassword",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
