class ErrorCode:
  VALIDATION_ERROR = "VALIDATION_ERROR"
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
  LOGIN_FAIL = "LOGIN_FAIL"
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
