from app.common.message import ErrorMessage

VALIDATION_MESSAGES = {
    # 認証関連
    ("username", "missing"): ErrorMessage.USERNAME_REQUIRED,
    ("password", "missing"): ErrorMessage.PASSWORD_REQUIRED,
    ("username", "too_long"): ErrorMessage.USERNAME_MAX_LENGTH,
    ("password", "string_too_short"): ErrorMessage.PASSWORD_MIN_LENGTH,
    ("password", "string_too_long"): ErrorMessage.PASSWORD_MAX_LENGTH,
    ("username", "value_error"): ErrorMessage.USERNAME_FORMAT_EMAIL,
    # アカウント関連
    ("account_name", "missing"): ErrorMessage.ACCOUNT_NAME_REQUIRED,
    ("account_name", "string_too_long"): ErrorMessage.ACCOUNT_NAME_MAX_LENGTH,
    ("account_name", "string_too_short"): ErrorMessage.ACCOUNT_NAME_REQUIRED,
    ("account_name", "value_error"): ErrorMessage.ACCOUNT_NAME_BLANK,
    ("current_password", "missing"): ErrorMessage.PASSWORD_REQUIRED,
    ("current_password", "string_too_short"): ErrorMessage.PASSWORD_MIN_LENGTH,
    ("current_password", "string_too_long"): ErrorMessage.PASSWORD_MAX_LENGTH,
    ("new_password", "missing"): ErrorMessage.PASSWORD_REQUIRED,
    ("new_password", "string_too_short"): ErrorMessage.PASSWORD_MIN_LENGTH,
    ("new_password", "string_too_long"): ErrorMessage.PASSWORD_MAX_LENGTH,
    ("current_email", "missing"): ErrorMessage.USERNAME_REQUIRED,
    ("current_email", "value_error"): ErrorMessage.USERNAME_FORMAT_EMAIL,
    ("new_email", "missing"): ErrorMessage.USERNAME_REQUIRED,
    ("new_email", "value_error"): ErrorMessage.USERNAME_FORMAT_EMAIL,
    # 記事関連
    ("title", "missing"): ErrorMessage.TITLE_REQUIRED,
    ("body", "title_required_for_published"): ErrorMessage.TITLE_REQUIRED_FOR_PUBLISHED,
    ("title", "string_too_long"): ErrorMessage.TITLE_MAX_LENGTH,
    ("content_md", "missing"): ErrorMessage.CONTENT_MARKDOWN_REQUIRED,
    ("content_md", "size_over"): ErrorMessage.CONTENT_MARKDOWN_SIZE_OVER,
    ("content_html", "missing"): ErrorMessage.CONTENT_HTML_REQUIRED,
    ("thumbnail_url", "string_too_long"): ErrorMessage.THUMBNAIL_URL_MAX_LENGTH,
    ("status", "missing"): ErrorMessage.STATUS_REQUIRED,
    ("status", "literal_error"): ErrorMessage.STATUS_ENUM,
    ("images", "list_type"): ErrorMessage.IMAGES_ARRAY,
    ("images", "int_parsing"): ErrorMessage.IMAGES_VALUE,
    ("tags", "list_type"): ErrorMessage.TAGS_ARRAY,
    ("tags", "list_too_long"): ErrorMessage.TAGS_ARRAY_MAX_LENGTH,
    ("tags", "string_too_long"): ErrorMessage.TAGS_MAX_LENGTH,
    ("keyword", "string_too_long"): ErrorMessage.KEYWORD_MAX_LENGTH,
    ("offset", "greater_than_equal"): ErrorMessage.MIN_OFFSET,
    ("limit", "greater_than_equal"): ErrorMessage.MIN_LIMIT,
    ("limit", "less_than_equal"): ErrorMessage.MAX_LIMIT,
    ("post_id", "missing"): ErrorMessage.POST_ID_REQUIRED,
    ("post_id", "greater_than_equal"): ErrorMessage.MIN_POST_ID,
    ("image_id", "missing"): ErrorMessage.IMAGE_ID_REQUIRED,
    ("image_id", "greater_than_equal"): ErrorMessage.MIN_IMAGE_ID,
    ("page", "greater_than_equal"): ErrorMessage.MIN_PAGE,
}
